"""added relationship between user and task tables

Revision ID: 41a4b70100fa
Revises: 8ed673d36d36
Create Date: 2026-02-12 23:00:22.142248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a4b70100fa'
down_revision: Union[str, Sequence[str], None] = '8ed673d36d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Fill existing NULL values
    op.execute("""
        UPDATE tasks
        SET owner_id = (
            SELECT id FROM users LIMIT 1
        )
        WHERE owner_id IS NULL
    """)

    # 2️⃣ Now make it NOT NULL
    op.alter_column(
        'tasks',
        'owner_id',
        existing_type=sa.UUID(),
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
