"""created models for proeject and attached it to nested tasks

Revision ID: 7e1940f1967e
Revises: 0f75a4770009
Create Date: 2026-02-20 10:44:43.651271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1940f1967e'
down_revision: Union[str, Sequence[str], None] = '0f75a4770009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
