"""created models for proeject and attached it to nested tasks

Revision ID: ad46bed0b17c
Revises: 7e1940f1967e
Create Date: 2026-02-20 10:46:29.288312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad46bed0b17c'
down_revision: Union[str, Sequence[str], None] = '7e1940f1967e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
